version: 2
jobs:
  readmes:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn build

  node:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd node/cli-app && yarn
      - run: cd node/graphql && yarn
      - run: cd node/graphql-auth && yarn
      - run: cd node/graphql-schema-delegation && yarn
      - run: cd node/graphql-subscriptions && yarn
      - run: cd node/rest-express && yarn
      - run: cd node/script && yarn

workflows:
  version: 2
  build:
    jobs:
      - readmes
      - node