version: 2
jobs:
  readmes:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn build

  node:
    docker:
      - image: circleci/node
    working_directory: ~/project/node
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: cd cli-app && yarn

workflows:
  version: 2
  build:
    jobs:
      - readmes
      - node