version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd flow-graphql && yarn
      - run: cd flow-graphql && yarn flow version
      - run: cd flow-graphql && yarn flow 
