version: 2
jobs:
  readmes:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn build

  node:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd node/cli-app && yarn
      - run: cd node/graphql && yarn
      - run: cd node/graphql-auth && yarn
      - run: cd node/graphql-schema-delegation && yarn
      - run: cd node/graphql-subscriptions && yarn
      - run: cd node/rest-express && yarn
      - run: cd node/script && yarn

  typescript:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install -g typescript
      - run: cd typescript/circleci && yarn && tsc
      - run: cd typescript/cli-app && yarn && tsc
      - run: cd typescript/graphql && yarn && tsc
      - run: cd typescript/graphql-auth && yarn && tsc
      - run: cd typescript/graphql-schema-delegation && yarn && tsc
      - run: cd typescript/graphql-subscriptions && yarn && tsc
      - run: cd typescript/script && yarn && tsc

workflows:
  version: 2
  build:
    jobs:
      - readmes
      - node
      - typescript