version: 2
jobs:
  meta:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd .github/tests && yarn && yarn test

  node:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo yarn global add prisma
      - run: cd node/cli-app && yarn && prisma generate
      - run: cd node/graphql && yarn && prisma generate
      - run: cd node/graphql-auth && yarn && prisma generate
      - run: cd node/graphql-schema-delegation && yarn && prisma generate
      - run: cd node/graphql-subscriptions && yarn && prisma generate
      - run: cd node/rest-express && yarn && prisma generate
      - run: cd node/script && yarn && prisma generate

  typescript:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo yarn global add prisma
      # - run: cd typescript/circleci && yarn && yarn tsc
      - run: cd typescript/cli-app && yarn && prisma generate && yarn tsc
      - run: cd typescript/graphql && yarn && prisma generate && yarn generate && yarn tsc
      - run: cd typescript/graphql-auth && yarn && prisma generate && yarn generate && yarn tsc
      - run: cd typescript/graphql-subscriptions && yarn && prisma generate && yarn generate && yarn tsc
      - run: cd typescript/script && yarn && prisma generate && yarn tsc

  flow:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo yarn global add prisma
      - run: cd flow/graphql && yarn && prisma generate && yarn generate && yarn flow check
      - run: cd flow/script && yarn && prisma generate && yarn flow check

  go:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/prisma/prisma-examples
    steps:
      - checkout
      - run: curl https://s3-eu-west-1.amazonaws.com/homebrew-prisma/prisma-1.21.0.tar.gz | tar xvz && mv prisma /usr/local/bin # TODO (see https://github.com/prisma/prisma/issues/3620)
      - run: cd go/cli-app && prisma generate && dep ensure && go build
      - run: cd go/graphql && prisma generate && dep ensure && go run ./scripts/gqlgen.go && go build
      - run: cd go/http-mux && prisma generate && dep ensure && go build
      - run: cd go/rest-gin && prisma generate && dep ensure && go build
      - run: cd go/script && prisma generate && dep ensure && go build

workflows:
  version: 2
  build:
    jobs:
      - meta
      - node
      - typescript
      - flow
      - go
