# Defines your models, each model is mapped to the database as a table.
datamodel: datamodel.prisma

# Specifies the language and directory for the generated Prisma client.
generate:
  - generator: flow-client
    output: ../src/generated/prisma-client/

# Ensure Prisma client is re-generated after a datamodel change.
hooks:
  post-deploy:
    - prisma generate

# Seed initial data into the database by running a script.
seed:
  - run: node seed.js