projects:
  db:
    schemaPath: generated-schema.graphql
    extensions:
      endpoints:
        default: 'http://localhost:4466/hooks'
      prisma: prisma.yml
      codegen:
        output: 
          typings: generated-prisma.ts
        generator: typegen
        language: typescript
